## YAML Template.
---
parameters:
    # Oxygen contact email address
    oxygen_blog.emails.contact_email: mark@oxygenthinking.com
    # Oxygen max latest comments
    oxygen_blog.comments.latest_comment_limit: 10