BloggerBlogBundle_homepage:
  pattern:  /
  defaults: { _controller: BloggerBlogBundle:Page:index }
  requirements:
    _method: GET
      
BloggerBlogBundle_about:
  pattern: /about
  defaults: { _controller: BloggerBlogBundle:Page:about }
  
BloggerBlogBundle_contact:
  pattern: /contact
  defaults: { _controller: BloggerBlogBundle:Page:Contact }
  requirements:
    _method: GET|POST
    
BloggerBlogBundle_blog_show:
    pattern:  /show/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:show }
    requirements:
        _method:  GET
        id: \d+
        
BloggerBlogBundle_comment_create:
    pattern:  /comment/{blog_id}
    defaults: { _controller: BloggerBlogBundle:Comment:create }
    requirements:
        _method:  POST
        blog_id: \d+
        
BloggerBlogBundle_blog_create:
    pattern: /admin/blog/create
    defaults: { _controller: BloggerBlogBundle:Blog:create }
    requirements:
        _method:  POST|GET
        
BloggerBlogBundle_blog_edit:
    pattern: /admin/blog/edit/{id}
    defaults: { _controller: BloggerBlogBundle:Blog:edit }
    
switch_user:
  pattern: /?_switch_user={user}
  defaults: { _controller: BloggerBlogBundle:Page:index }
  
BloggerBlogBundle_blog_delete:
  pattern:  /{id}/delete
  defaults: { _controller: BloggerBlogBundle:Blog:delete }
  requirements: { _method: post }
  
BloggerBlogBundle_blog_category:
  pattern: /{category}
  defaults: { _controller: BloggerBlogBundle:Blog:blogsByCategory }