parameters:
#    oxygen_blog.example.class: Oxygen\BlogBundle\Example

services:
#    oxygen_blog.example:
#        class: %oxygen_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
